### ISSUE TITLE
Improve summary

### ISSUE THREAD

**Issue by razzeee** [flathub/io.github.loot.loot#1]
Hey, 

please have a look at https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/ and consider shortening the summary and removing the period

**Comment by Ortham** [comment]
I've already got going through that page on my to do list. I can't think of a useful summary that's under 35 characters though. Also, the current summary is the same one that's used elsewhere, and I think the consistency is a good thing (though if there is a good short summary, I could use that elsewhere too).

**Comment by razzeee** [comment]
I would start with something like `Load order optimisation for Elder Scrolls and Fallout games` - the point of the summary is to draw people in to reading your description after all, you can name drop all games there. (yeah it's still too long)

I do agree, that 35 is short, but that's probably by design to force you to make a hard choice and thus have a better - more likely read text.

**Comment by Ortham** [comment]
> I would start with something like `Load order optimisation for Elder Scrolls and Fallout games` - the point of the summary is to draw people in to reading your description after all, you can name drop all games there. (yeah it's still too long)
> 
> I do agree, that 35 is short, but that's probably by design to force you to make a hard choice and thus have a better - more likely read text.

I don't really care about drawing people in through the Flathub listing though, it's a very niche utility that is already very well-known in that niche. Approximately nobody is going to discover LOOT by browsing Flathub, it's just a way to provide a consistent and good installation experience for the handful of people who are going to run it as a native Linux application.

**Comment by razzeee** [comment]
That's fine, but at some point, we might block apps that don't reach this minimal quality from appearing on the frontpage.
Just FYI. I would still appreciate, if you could remove the punctuation.

**Comment by Ortham** [comment]
> That's fine, but at some point, we might block apps that don't reach this minimal quality from appearing on the frontpage. Just FYI. I would still appreciate, if you could remove the punctuation.

That's reasonable, and I'll remove the punctuation as part of my sweep through those quality guidelines (I also need a couple of better screenshots).

I think the only other thing in the guidelines that I'm not sure about is the bit about release notes: I've already got nearly a decade of release notes [here](https://loot.readthedocs.io/en/latest/app/changelog.html) and I'm not going to be duplicating them in the metainfo XML file for the current or future releases, but if I add a [`<url>`](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Releases.html#tag-release-url) element pointing to the release notes hosted on readthedocs, how will that get displayed?

**Comment by razzeee** [comment]
We only display the latest release note (on the website). Software centers might allow more.
The website will show the url as a link to `Additional Information` and can handle it being the only thing (besides the version)

But if I recently read the appstream data spec correctly, they say, that `url` should be in addition and at least some of the bulletpoints should be in the release tag.

If I were you, I would add new release notes to my appstream, but don't add anything retrospective, as those builds are not on flathub anyway, documenting them in the appstream seems not necessary. Unless you want to do that for other places, where you reuse the appstream data.

**Comment by Ortham** [comment]
Hmm, reading the spec again my impression is that the description is optional but should be a high-level description of the release as a whole (i.e. just mentioning the main changes). I don't currently do that elsewhere so adding that to the metainfo wouldn't be duplicating anything.

Thanks for the info!

**Comment by Ortham** [comment]
Closing this as I've shortened the summary in 63fd3650989a9f733f9b48ec06fb0e8b1f994034 and it should be reflected on the site in a few hours.
